create table if not exists sims (
    sim_id text primary key,
    registered_at text,
    offense_count integer default 0,
    risk_score integer default 0,
    ban_level integer default 0,
    ban_start text default '',
    ban_expires text default '',
    is_permanently_blocked boolean default false,
    appeal_status text default 'NONE',
    appeal_reason text default '',
    last_offense_at text default '',
    last_case_id text default ''
);

create table if not exists notifications (
    id bigint generated by default as identity primary key,
    timestamp text,
    sim_id text,
    notification_type text,
    message text,
    penalty_level integer,
    ban_duration text
);

create table if not exists fraud_cases (
    case_id text primary key,
    sim_id text,
    created_at text,
    fraud_probability numeric,
    risk_level text,
    fraud_status text,
    actions text,
    status text,
    defense_status text,
    threat_tier text,
    blocked_components text,
    shutdown_components text,
    enforced_at text,
    penalty_level integer,
    ban_duration text,
    risk_score integer,
    offense_count integer,
    age integer,
    account_age_days integer,
    calls_per_day integer,
    avg_call_duration numeric,
    unique_numbers_called integer,
    international_calls integer,
    sms_per_day integer,
    data_usage_gb numeric,
    recharge_amount numeric,
    sim_changes integer,
    device_changes integer,
    complaints_count integer,
    roaming_usage integer,
    late_payments integer,
    appeal_reason text default '',
    appeal_submitted_at text default ''
);

create table if not exists defense_logs (
    id bigint generated by default as identity primary key,
    timestamp text,
    sim_id text,
    case_id text,
    threat_tier text,
    component text,
    action text,
    status text,
    detail text,
    penalty_level integer,
    risk_score integer
);

create table if not exists appeals (
    id bigint generated by default as identity primary key,
    case_id text,
    sim_id text,
    appeal_reason text,
    appeal_status text default 'PENDING',
    submitted_at text,
    resolved_at text default '',
    admin_decision text default ''
);

create index if not exists idx_fraud_cases_sim_id on fraud_cases(sim_id);
create index if not exists idx_defense_logs_sim_id on defense_logs(sim_id);
create index if not exists idx_appeals_sim_id on appeals(sim_id);

alter table sims disable row level security;
alter table notifications disable row level security;
alter table fraud_cases disable row level security;
alter table defense_logs disable row level security;
alter table appeals disable row level security;


create table if not exists sim_customers (
    sim_id text primary key,
    full_name text not null,
    nrc text not null,
    location text not null,
    phone_number text default '',
    email text default '',
    status text default 'ACTIVE',
    registered_at text
);

create index if not exists idx_sim_customers_phone_number on sim_customers(phone_number);
create index if not exists idx_sim_customers_nrc on sim_customers(nrc);

alter table sim_customers disable row level security;


create table if not exists public.admin_users (
    id bigserial primary key,
    username text unique not null,
    email text unique not null,
    full_name text,
    role text default 'Administrator',
    password_hash text not null,
    salt text not null,
    is_active boolean default true,
    created_at text,
    last_login_at text
);

alter table public.admin_users disable row level security;
